# Generated by Django 5.0.2 on 2024-02-10 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=70, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElementPhoto', models.ImageField(upload_to='elphoto/', verbose_name='Фото элемента')),
                ('ElementDate', models.DateField(verbose_name='Дата')),
                ('ElementName', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('PagePhoto', models.ImageField(upload_to='mainphoto/', verbose_name='Фото страницы')),
                ('PageText', models.TextField(verbose_name='Основной текст статьи')),
                ('Categoryselect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAppMain.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Наполнение',
                'verbose_name_plural': 'Наполнение',
            },
        ),
    ]
